#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Geometry was generated in octave".
echo "Check the octave folder for generating new geometries."

# Create mesh
runApplication blockMesh
runApplication snappyHexMesh -overwrite

# Run simlpeFoam
cp system/residualControl.simple system/residualControl
runApplication simpleFoam

# Copy last time velocity and clean times
foamEndTime=$(foamListTimes -latestTime)
mv $foamEndTime/U 0/.
foamListTimes -rm

# Run scalarTransportFoam
cp system/residualControl.scalar system/residualControl
runApplication scalarTransportFoam
