#!/bin/bash

echo "Usage: ./Allrun packing_type porosity resolution"


. $WM_PROJECT_DIR/bin/tools/RunFunctions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -r 0
cp -r 0.init 0

cd system
python create_geometry.py $1 $2 1 $3 1 1
cd ..
runApplication blockMesh
runApplication snappyHexMesh -overwrite
runApplication createPatch -overwrite
cp  0.init/* 0/.
runApplication simpleFoam
foamEndTime=$(foamListTimes | tail -1)
if [ -d $foamEndTime ]; then
   mkdir 0.end
   mv $foamEndTime/U 0/.
   rm -r $foamEndTime
fi
runApplication ADRCellFoam
