#!/bin/bash
rm -rf constant/polyMesh
cd ${0%/*} || exit 1    # run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application=`getApplication`

echo "Meshing"
cp system/blockMeshDict_periodic /system/blockMeshDict
blockMesh

snappyHexMesh -overwrite
cp system/createPatchDict3D system/createPatchDict
createPatch -overwrite
renumberMesh -overwrite

echo "Solving"
rm -rf 0
cp -r 0.periodic 0

if [ $1 != "None" ]
then
  mapFields $2 -consistent -sourceTime latestTime
fi

$application

touch paraview.foam
./qoi.sh log

# ----------------------------------------------------------------- end-of-file
