#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Create the mesh
runApplication blockMesh

# Create solid cell set(s)
runApplication topoSet

# Transform mesh to a domain of (1400 x 800 x 800nm)
runApplication transformPoints -scale "(1e-7 1e-7 1e-7)"

# Split mesh into solid and fluid regions, construct interface patches (fluid_to_solid, solid_to_fluid)
runApplication splitMeshRegions -cellZones -defaultRegionName fluid -overwrite

#------------------------------------------------------------------------------
