#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf breakthrough
rm -rf log.*

foamListTimes -rm
runApplication EqRetCellFoam
