#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials
rm -rf breakthrough

# Create mesh
runApplication blockMesh
#runApplication decomposePar
runApplication snappyHexMesh -overwrite
runApplication createPatches -overwrite
rm -f 0/T

# Run simlpeFoam
cp 0.simple/* 0/
cp system/controlDict.simpleFoam system/controlDict
cp system/residualControl.simple system/residualControl
runApplication simpleFoam
find . -name 'phi' -exec rm -rf {} \;
