#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials
rm -rf breakthrough

# Create mesh
runApplication blockMesh
#runApplication decomposePar
runApplication snappyHexMesh -overwrite
runApplication createPatch -overwrite
rm -f 0/T

# Run simlpeFoam
cp 0.simple/* 0/
cp system/controlDict.simpleFoam system/controlDict
cp system/residualControl.simple system/residualControl
runApplication simpleFoam
find . -name 'phi' -exec rm -rf {} \;

sed -i 's/cyclic/patch/g' constant/polyMesh/boundary
#for i in proc*
#do
#  sed -i 's/cyclic/symmetry/g' $i/constant/polyMesh/boundary
#  sed -i 's/cyclic/symmetry/g' $i/0/*
#done

foamEndTime=$(foamListTimes -latestTime)
mv $foamEndTime/U 0/.
sed -i 's/cyclic/zeroGradient/g' 0/*
foamListTimes -rm
cp system/controlDict.scalar system/controlDict
cp 0.scalar/* 0/
cp system/residualControl.scalar system/residualControl
runApplication scalarTransportFoam
